Repository minishelll/deepshell, pull requests merged in 2024-04, with the labels that each got.

#23 Fix: add setting of accept
  src/manda/parser/insert_data.h
  src/manda/parser/insert_lr_table.c
Labels: Fix

#28 [Fix] Dev/main과 수정된 Tokenizer 병합
  src/manda/parser/tokenizer.c
  src/manda/parser/tokenizer_op_parser.c
  src/manda/parser/tokenizer_quote_parser.c
  src/manda/parser/tokenizer_utils.c
Labels: Fix

#30 Build : seperate parser header & move insert_* to insert_data/
  .gitignore
  src/manda/Makefile
  src/manda/include/input_type.h
  src/manda/insert_data/Makefile
  src/manda/insert_data/insert_data.h
  src/manda/insert_data/insert_grammar.c
  src/manda/insert_data/insert_grammar.h
  src/manda/insert_data/insert_lr_table.c
  src/manda/insert_data/insert_lr_table.h
  src/manda/insert_data/insert_util.c
  src/manda/main_syntax_analyzer_print.c
  src/manda/parser/Makefile
  src/manda/parser/syntax_analyzer.h
  src/manda/parser/tokenizer.c
  src/manda/parser/tokenizer.h
  src/manda/parser/tokenizer_op_parser.c
  src/manda/parser/tokenizer_quote_parser.c
  src/manda/parser/tokenizer_utils.c
Labels: Build

#31 Dev/semantic analyzer
  src/manda/Makefile
  src/manda/insert_data/insert_grammar.c
  src/manda/insert_data/insert_lr_table.c
  src/manda/main_syntax_analyzer_print.c
  src/manda/parser/Makefile
  src/manda/parser/semantic_analyzer.c
  src/manda/parser/semantic_analyzer.h
  src/manda/parser/semantic_analyzer_utils.c
  src/manda/parser/syntax_analyzer.c
  src/manda/parser/syntax_analyzer.h
  src/manda/parser/syntax_lr_stack.c
  src/manda/parser/syntax_tree.h
  src/manda/print.c
Labels: Feat

#39 [[RE]] Dev/built in & [FEAT]expand & [FIX]execute
  include_make/Variable.mk
  src/manda/Makefile
  src/manda/built_in/Makefile
  src/manda/built_in/built_in.c
  src/manda/built_in/built_in.h
  src/manda/built_in/built_in_env.c
  src/manda/built_in/built_in_other.c
  src/manda/envlist.c
  src/manda/envlist/Makefile
  src/manda/envlist/envlist.c
  src/manda/envlist/envlist.h
  src/manda/envlist/envlist_util.c
  src/manda/execute/execute.c
  src/manda/execute/execute.h
  src/manda/execute/execute_child_process.c
  src/manda/execute/execute_command.c
  src/manda/execute/execute_pipe.c
  src/manda/execute/execute_redirect.c
  src/manda/execute/execute_subshell.c
  src/manda/execute/execute_utils.c
  src/manda/execute/expand.c
  src/manda/ft_error/ft_error.c
  src/manda/ft_error/ft_error.h
  src/manda/include/minishell.h
  src/manda/main.c
  src/manda/parser/Makefile
  src/manda/parser/expand.c
  src/manda/parser/parser.c
  src/manda/parser/parser.h
  src/manda/parser/syntax_analyzer.c
  src/manda/parser/syntax_analyzer.h
  src/manda/parser/syntax_analyzer_util.c
  src/manda/parser/tokenizer.c
  src/manda/parser/tokenizer.h
  src/manda/print.c
  src/manda/print_welcome_title.c
Labels: Fix, Feat

#43 Dev/signal
  eof
  src/manda/Makefile
  src/manda/execute/execute.c
  src/manda/execute/execute_child_process.c
  src/manda/execute/execute_utils.c
  src/manda/main.c
  src/manda/parser/tokenizer.c
  src/manda/parser/tokenizer_utils.c
  src/manda/signal/Makefile
  src/manda/signal/mini_signal.c
  src/manda/signal/mini_signal.h
  src/manda/signal/mini_terminal.c
Labels: Feat
